apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  annotations:
    machine.openshift.io/instance-state: running
  creationTimestamp: "2026-04-18T02:33:16Z"
  finalizers:
  - machine.machine.openshift.io
  generateName: ci-ln-0mi9cpt-76ef8-8g76q-worker-us-west-2a-m7a-
  generation: 2
  labels:
    machine.openshift.io/cluster-api-cluster: ci-ln-0mi9cpt-76ef8-8g76q
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
    machine.openshift.io/cluster-api-machineset: ci-ln-0mi9cpt-76ef8-8g76q-worker-us-west-2a-m7a
    machine.openshift.io/instance-type: m7a.xlarge
    machine.openshift.io/region: us-west-2
    machine.openshift.io/zone: us-west-2a
  name: ci-ln-0mi9cpt-76ef8-8g76q-worker-us-west-2a-m7a-9s2sr
  namespace: openshift-machine-api
  ownerReferences:
  - apiVersion: machine.openshift.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: MachineSet
    name: ci-ln-0mi9cpt-76ef8-8g76q-worker-us-west-2a-m7a
    uid: bed94fc2-6447-4b3d-b481-7b2de9463f3f
  resourceVersion: "37682"
  uid: 42206e2c-abc1-4c6c-92cb-0ba3ba0aa12c
spec:
  lifecycleHooks: {}
  metadata: {}
  providerID: aws:///us-west-2a/i-03f1acaabe7a34dfd
  providerSpec:
    value:
      ami:
        id: ami-04941543f3e575579
      apiVersion: machine.openshift.io/v1beta1
      blockDevices:
      - ebs:
          encrypted: true
          iops: 0
          kmsKey:
            arn: ""
          volumeSize: 120
          volumeType: gp3
      capacityReservationId: ""
      credentialsSecret:
        name: aws-cloud-credentials
      deviceIndex: 0
      iamInstanceProfile:
        id: ci-ln-0mi9cpt-76ef8-8g76q-worker-profile
      instanceType: m7a.xlarge
      kind: AWSMachineProviderConfig
      metadata: {}
      metadataServiceOptions: {}
      placement:
        availabilityZone: us-west-2a
        region: us-west-2
      securityGroups:
      - filters:
        - name: tag:Name
          values:
          - ci-ln-0mi9cpt-76ef8-8g76q-node
      - filters:
        - name: tag:Name
          values:
          - ci-ln-0mi9cpt-76ef8-8g76q-lb
      subnet:
        filters:
        - name: tag:Name
          values:
          - ci-ln-0mi9cpt-76ef8-8g76q-subnet-private-us-west-2a
      tags:
      - name: kubernetes.io/cluster/ci-ln-0mi9cpt-76ef8-8g76q
        value: owned
      - name: ci-nat-replace
        value: "true"
      - name: clusterName
        value: ci-ln-0mi9cpt-76ef8
      - name: expirationDate
        value: 2026-04-18T09:29+00:00
      userDataSecret:
        name: worker-user-data
status:
  addresses:
  - address: 10.0.49.250
    type: InternalIP
  - address: ip-10-0-49-250.us-west-2.compute.internal
    type: InternalDNS
  - address: ip-10-0-49-250.us-west-2.compute.internal
    type: Hostname
  conditions:
  - lastTransitionTime: "2026-04-18T02:33:17Z"
    status: "True"
    type: Drainable
  - lastTransitionTime: "2026-04-18T02:33:49Z"
    status: "True"
    type: InstanceExists
  - lastTransitionTime: "2026-04-18T02:33:17Z"
    status: "True"
    type: Terminable
  lastUpdated: "2026-04-18T02:37:35Z"
  nodeRef:
    kind: Node
    name: ip-10-0-49-250.us-west-2.compute.internal
    uid: 25352873-ec31-44ad-806c-09a1badf4528
  phase: Running
  providerStatus:
    conditions:
    - lastTransitionTime: "2026-04-18T02:33:19Z"
      message: Machine successfully created
      reason: MachineCreationSucceeded
      status: "True"
      type: MachineCreation
    instanceId: i-03f1acaabe7a34dfd
    instanceState: running
