apiVersion: v1
kind: Node
metadata:
  annotations:
    cloud.network.openshift.io/egress-ipconfig: '[{"interface":"eni-017ee8d37b20eadeb","ifaddr":{"ipv4":"10.0.0.0/18"},"capacity":{"ipv4":19,"ipv6":20}}]'
    csi.volume.kubernetes.io/nodeid: '{"ebs.csi.aws.com":"i-0d2c0f8d34d00e6dd"}'
    k8s.ovn.org/host-cidrs: '["10.0.6.113/18"]'
    k8s.ovn.org/l3-gateway-config: '{"default":{"mode":"shared","bridge-id":"br-ex","interface-id":"br-ex_ip-10-0-6-113.us-west-2.compute.internal","mac-address":"06:20:53:5c:59:f9","ip-addresses":["10.0.6.113/18"],"ip-address":"10.0.6.113/18","next-hops":["10.0.0.1"],"next-hop":"10.0.0.1","node-port-enable":"true","vlan-id":"0"}}'
    k8s.ovn.org/layer2-topology-version: "2.0"
    k8s.ovn.org/node-chassis-id: 6b507bcc-4018-445c-ac7a-4f39a51fdb52
    k8s.ovn.org/node-encap-ips: '["10.0.6.113"]'
    k8s.ovn.org/node-id: "11"
    k8s.ovn.org/node-masquerade-subnet: '{"ipv4":"169.254.0.0/17","ipv6":"fd69::/112"}'
    k8s.ovn.org/node-primary-ifaddr: '{"ipv4":"10.0.6.113/18"}'
    k8s.ovn.org/node-subnets: '{"default":["10.129.4.0/23"]}'
    k8s.ovn.org/node-transit-switch-port-ifaddr: '{"ipv4":"100.88.0.11/16"}'
    k8s.ovn.org/zone-name: ip-10-0-6-113.us-west-2.compute.internal
    machine.openshift.io/machine: openshift-machine-api/ci-ln-0mi9cpt-76ef8-8g76q-worker-us-west-2a-m8a-fvmnt
    machineconfiguration.openshift.io/controlPlaneTopology: HighlyAvailable
    machineconfiguration.openshift.io/currentConfig: rendered-worker-6b395dd44e0eb4af3df963ebb8c0b4de
    machineconfiguration.openshift.io/desiredConfig: rendered-worker-6b395dd44e0eb4af3df963ebb8c0b4de
    machineconfiguration.openshift.io/desiredDrain: uncordon-rendered-worker-6b395dd44e0eb4af3df963ebb8c0b4de
    machineconfiguration.openshift.io/lastAppliedDrain: uncordon-rendered-worker-6b395dd44e0eb4af3df963ebb8c0b4de
    machineconfiguration.openshift.io/lastObservedServerCAAnnotation: "false"
    machineconfiguration.openshift.io/lastSyncedControllerConfigResourceVersion: "54596"
    machineconfiguration.openshift.io/reason: ""
    machineconfiguration.openshift.io/state: Done
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2026-04-18T03:42:05Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: m8a.xlarge
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: us-west-2
    failure-domain.beta.kubernetes.io/zone: us-west-2a
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: ip-10-0-6-113.us-west-2.compute.internal
    kubernetes.io/os: linux
    node-role.kubernetes.io/worker: ""
    node.kubernetes.io/instance-type: m8a.xlarge
    node.openshift.io/os_id: rhel
    topology.ebs.csi.aws.com/zone: us-west-2a
    topology.k8s.aws/zone-id: usw2-az2
    topology.kubernetes.io/region: us-west-2
    topology.kubernetes.io/zone: us-west-2a
  name: ip-10-0-6-113.us-west-2.compute.internal
  resourceVersion: "62754"
  uid: 3ed48599-f9a8-42a9-87a3-c601709dadeb
spec:
  providerID: aws:///us-west-2a/i-0d2c0f8d34d00e6dd
status:
  addresses:
  - address: 10.0.6.113
    type: InternalIP
  - address: ip-10-0-6-113.us-west-2.compute.internal
    type: InternalDNS
  - address: ip-10-0-6-113.us-west-2.compute.internal
    type: Hostname
  allocatable:
    cpu: 3500m
    ephemeral-storage: "114345831029"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 14886056Ki
    pods: "250"
  capacity:
    cpu: "4"
    ephemeral-storage: 125238252Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 16037032Ki
    pods: "250"
  conditions:
  - lastHeartbeatTime: "2026-04-18T03:43:57Z"
    lastTransitionTime: "2026-04-18T03:42:05Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2026-04-18T03:43:57Z"
    lastTransitionTime: "2026-04-18T03:42:05Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2026-04-18T03:43:57Z"
    lastTransitionTime: "2026-04-18T03:42:05Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2026-04-18T03:43:57Z"
    lastTransitionTime: "2026-04-18T03:42:39Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  features:
    supplementalGroupsPolicy: true
  images:
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:98e1cc6188fc1cb73ac2110278ed8ad37f63c352dd3674a9a2330d0ce7a8962f
    sizeBytes: 1434948575
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:f2a881575eebd6159e28871d61fcae25d41f9161b8cb403f6f3b8421fd0cca0c
    sizeBytes: 1190956054
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:af9fcc6054c6a2f327b0936175b9abf6ca10f561b4622a9ae45d983bc88b74dc
    sizeBytes: 1064998491
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:a43f56d746c295cf66c958489d98d7b7f302f1c59181bb5b39bd19cf8b2ba450
    sizeBytes: 885876624
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:6dcee6a963ce8f874f9c9b03bb586f6fcdf34da7b1ec28d5e9a9e35777949577
    sizeBytes: 590144933
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:840f4233be59e903894cc4829ef32536bab4e55e8fd646fcaf31b5405758ee51
    sizeBytes: 547477081
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8f38921df5929f15eed801fdb39b5212bb08b83e25089ac1ff5296c03b900532
    sizeBytes: 532484060
  - names:
    - quay.io/openshift-logging/promtail@sha256:37c4c781fb99ad787118c4ebebc1d81ac6415ba62c4d5965e3852e5721509909
    - quay.io/openshift-logging/promtail@sha256:f0e53a97d686fdab3ae1a4b43176dd0105ce53887b0faba528f3497f7765d26f
    - quay.io/openshift-logging/promtail:v2.9.8
    sizeBytes: 478481622
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:db4b1920bd3e00a2cc1ee6a853cb6733b6a6b2bca4c32d0fbcd99ae9a8318326
    sizeBytes: 465913813
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1ad836c160a58eef5cdf48bb53d8f0229e6378b41213a71c2af4edfb91a231b6
    sizeBytes: 358917271
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4e343d823d1bae702f0e7156e75a0fdcd551da2752731df144fec7b606543e1e
    sizeBytes: 356285197
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ddc8442fd18f636dc965ae8bfe62666d181db93a1c4c4737ac93c28658ace973
    sizeBytes: 352755816
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b1d7fd03f9b2d8d25cf064dd09f5c5a1af34acc13f2a0fbdfed97a4e106337be
    sizeBytes: 339903047
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:0380726046c5c0aa952e870fddd0b10606027ef938f58677d07d5bdaf5a25b45
    sizeBytes: 327827345
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:95fc1c2f0c737ff4fe181283e4a10d003f099b004220e33e872c607dbaf174fa
    sizeBytes: 322644271
  - names:
    - registry.redhat.io/openshift4/ose-oauth-proxy-rhel9@sha256:eb7244813fd299cb3b125799b5a03bf93e75110308331f8db1e3cbae3d739b0e
    - registry.redhat.io/openshift4/ose-oauth-proxy-rhel9@sha256:f85223c9693ecb0e69e156fe28c980d0d4edeaf823142327b0a4033e0fc89074
    - registry.redhat.io/openshift4/ose-oauth-proxy-rhel9:latest
    sizeBytes: 304600334
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:90e97cf5a3d8993004a0632acb563a771c3ddfa1eacf78cc1f13e3232214dd47
    sizeBytes: 291014911
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8ed83b8250364f976ff1e3615e5319db83151410018c789e76eed958e77e57c0
    sizeBytes: 287817206
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:de59eb083de71bd060af81f20a3afd00eeac51d24f403e268203d28617ae4f04
    sizeBytes: 258415960
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:c289342d2e30bdc9c6aa5b1a916f7a19876b5b51b31c511ff701f27d49a38e57
    sizeBytes: 257191618
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3063fcdf3a5c051ab9cb6d941fefc4d8fbc837a9e56e942330169194327070f5
    sizeBytes: 245097412
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:29da7c22879c5fcd109aab4c466bddf1c8014555d44accbab28f098cabfcca9f
    sizeBytes: 244839380
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:38b63160286e879b538c7696671bd6a816f587dd8eea20ad2a95935e8a7dd0f2
    sizeBytes: 232308419
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:cbf568e97ab88324852febfc75e927178d1d660b42c695ac734fec4137bbde51
    sizeBytes: 227906096
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:506d643abca3d964e7436009cbff718767940595343a383430210ddd5d9f138f
    sizeBytes: 225096120
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7f54cb834e5ff02577b2ddc622ea8045542fb7cbebad1f5593870dce98bca0b7
    sizeBytes: 215981994
  - names:
    - quay.io/observatorium/token-refresher@sha256:1d99cf24a5a1d74daf73ac47b4e757f13ed5408e7441642bb7ad02bb71551841
    - quay.io/observatorium/token-refresher@sha256:721366017a72606d0022be291c40c300e7cdba2a45f79a485ce5790d865db47d
    - quay.io/observatorium/token-refresher:latest
    sizeBytes: 10461829
  nodeInfo:
    architecture: amd64
    bootID: d3563cda-851a-43f4-9b67-9a38b87f0ba8
    containerRuntimeVersion: cri-o://1.34.6-2.rhaos4.21.gitbca534a.el9
    kernelVersion: 5.14.0-570.107.1.el9_6.x86_64
    kubeProxyVersion: ""
    kubeletVersion: v1.34.6
    machineID: ec273a83f8eef71fb07d305cbd2b085f
    operatingSystem: linux
    osImage: Red Hat Enterprise Linux CoreOS 9.6.20260414-0 (Plow)
    systemUUID: ec273a83-f8ee-f71f-b07d-305cbd2b085f
  runtimeHandlers:
  - features:
      recursiveReadOnlyMounts: true
      userNamespaces: true
    name: runc
  - features:
      recursiveReadOnlyMounts: true
      userNamespaces: true
    name: crun
  - features:
      recursiveReadOnlyMounts: true
      userNamespaces: true
    name: ""
