apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  annotations:
    machine.openshift.io/instance-state: Running
  creationTimestamp: "2026-04-17T22:29:28Z"
  finalizers:
  - machine.machine.openshift.io
  generateName: ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3-
  generation: 2
  labels:
    machine.openshift.io/cluster-api-cluster: ci-ln-wy83gzk-1d09d-m9g8v
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
    machine.openshift.io/cluster-api-machineset: ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3
    machine.openshift.io/instance-type: Standard_D4s_v3
    machine.openshift.io/region: westus
  name: ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3-sfw9k
  namespace: openshift-machine-api
  ownerReferences:
  - apiVersion: machine.openshift.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: MachineSet
    name: ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3
    uid: c4ca2b07-9e76-4fe6-b8b2-1590b7c8278c
  resourceVersion: "49935"
  uid: 70041fb8-bb63-4b69-94aa-38cfc509c01a
spec:
  lifecycleHooks: {}
  metadata: {}
  providerID: azure:///subscriptions/72e3a972-58b0-4afc-bd4f-da89b39ccebd/resourceGroups/ci-ln-wy83gzk-1d09d-m9g8v-rg/providers/Microsoft.Compute/virtualMachines/ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3-sfw9k
  providerSpec:
    value:
      acceleratedNetworking: true
      apiVersion: machine.openshift.io/v1beta1
      credentialsSecret:
        name: azure-cloud-credentials
        namespace: openshift-machine-api
      diagnostics:
        boot:
          storageAccountType: AzureManaged
      image:
        offer: ""
        publisher: ""
        resourceID: /resourceGroups/ci-ln-wy83gzk-1d09d-m9g8v-rg/providers/Microsoft.Compute/galleries/gallery_ci_ln_wy83gzk_1d09d_m9g8v/images/ci-ln-wy83gzk-1d09d-m9g8v-gen2/versions/latest
        sku: ""
        version: ""
      kind: AzureMachineProviderSpec
      location: westus
      managedIdentity: ci-ln-wy83gzk-1d09d-m9g8v-identity
      metadata:
        creationTimestamp: null
      networkResourceGroup: ci-ln-wy83gzk-1d09d-m9g8v-rg
      osDisk:
        diskSettings: {}
        diskSizeGB: 128
        managedDisk:
          securityProfile:
            diskEncryptionSet: {}
          storageAccountType: Premium_LRS
        osType: Linux
      publicIP: false
      publicLoadBalancer: ci-ln-wy83gzk-1d09d-m9g8v
      resourceGroup: ci-ln-wy83gzk-1d09d-m9g8v-rg
      securityProfile:
        settings: {}
      subnet: ci-ln-wy83gzk-1d09d-m9g8v-worker-subnet
      tags:
        expiration_date: 2026-04-18T04:33+00:00
      userDataSecret:
        name: worker-user-data
      vmSize: Standard_D4s_v3
      vnet: ci-ln-wy83gzk-1d09d-m9g8v-vnet
status:
  addresses:
  - address: ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3-sfw9k
    type: Hostname
  - address: ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3-sfw9k
    type: InternalDNS
  - address: ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3-sfw9k.gvquxfmjinwupnjky3ja3qj0qh.dx.internal.cloudapp.net
    type: InternalDNS
  - address: 10.0.128.7
    type: InternalIP
  conditions:
  - lastTransitionTime: "2026-04-17T22:29:30Z"
    status: "True"
    type: Drainable
  - lastTransitionTime: "2026-04-17T22:29:40Z"
    status: "True"
    type: InstanceExists
  - lastTransitionTime: "2026-04-17T22:29:30Z"
    status: "True"
    type: Terminable
  lastUpdated: "2026-04-17T22:37:10Z"
  nodeRef:
    kind: Node
    name: ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3-sfw9k
    uid: 781a25f4-5641-4c1a-bac8-a2bdb19ff57b
  phase: Running
  providerStatus:
    conditions:
    - lastTransitionTime: "2026-04-17T22:29:38Z"
      message: machine successfully created
      reason: MachineCreationSucceeded
      status: "True"
      type: MachineCreated
    metadata: {}
    vmId: /subscriptions/72e3a972-58b0-4afc-bd4f-da89b39ccebd/resourceGroups/ci-ln-wy83gzk-1d09d-m9g8v-rg/providers/Microsoft.Compute/virtualMachines/ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3-sfw9k
    vmState: Running
