apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  annotations:
    machine.openshift.io/instance-state: running
  creationTimestamp: "2026-04-18T04:05:38Z"
  finalizers:
  - machine.machine.openshift.io
  generateName: ci-ln-0mi9cpt-76ef8-8g76q-worker-us-west-2a-m8a-
  generation: 2
  labels:
    machine.openshift.io/cluster-api-cluster: ci-ln-0mi9cpt-76ef8-8g76q
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
    machine.openshift.io/cluster-api-machineset: ci-ln-0mi9cpt-76ef8-8g76q-worker-us-west-2a-m8a
    machine.openshift.io/instance-type: m8a.xlarge
    machine.openshift.io/region: us-west-2
    machine.openshift.io/zone: us-west-2a
  name: ci-ln-0mi9cpt-76ef8-8g76q-worker-us-west-2a-m8a-bhrvg
  namespace: openshift-machine-api
  ownerReferences:
  - apiVersion: machine.openshift.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: MachineSet
    name: ci-ln-0mi9cpt-76ef8-8g76q-worker-us-west-2a-m8a
    uid: 8b1eba4b-acc4-43d0-a886-99b5b158efe3
  resourceVersion: "73437"
  uid: 785a0fd9-64a3-4072-ac02-9f8b7e7706b9
spec:
  lifecycleHooks: {}
  metadata: {}
  providerID: aws:///us-west-2a/i-0434f6b18f1017460
  providerSpec:
    value:
      ami:
        id: ami-04941543f3e575579
      apiVersion: machine.openshift.io/v1beta1
      blockDevices:
      - ebs:
          encrypted: true
          iops: 0
          kmsKey:
            arn: ""
          volumeSize: 120
          volumeType: gp3
      capacityReservationId: ""
      credentialsSecret:
        name: aws-cloud-credentials
      deviceIndex: 0
      iamInstanceProfile:
        id: ci-ln-0mi9cpt-76ef8-8g76q-worker-profile
      instanceType: m8a.xlarge
      kind: AWSMachineProviderConfig
      metadata: {}
      metadataServiceOptions: {}
      placement:
        availabilityZone: us-west-2a
        region: us-west-2
      securityGroups:
      - filters:
        - name: tag:Name
          values:
          - ci-ln-0mi9cpt-76ef8-8g76q-node
      - filters:
        - name: tag:Name
          values:
          - ci-ln-0mi9cpt-76ef8-8g76q-lb
      subnet:
        filters:
        - name: tag:Name
          values:
          - ci-ln-0mi9cpt-76ef8-8g76q-subnet-private-us-west-2a
      tags:
      - name: kubernetes.io/cluster/ci-ln-0mi9cpt-76ef8-8g76q
        value: owned
      - name: ci-nat-replace
        value: "true"
      - name: clusterName
        value: ci-ln-0mi9cpt-76ef8
      - name: expirationDate
        value: 2026-04-18T09:29+00:00
      userDataSecret:
        name: worker-user-data
status:
  addresses:
  - address: 10.0.63.189
    type: InternalIP
  - address: ip-10-0-63-189.us-west-2.compute.internal
    type: InternalDNS
  - address: ip-10-0-63-189.us-west-2.compute.internal
    type: Hostname
  conditions:
  - lastTransitionTime: "2026-04-18T04:05:38Z"
    status: "True"
    type: Drainable
  - lastTransitionTime: "2026-04-18T04:06:10Z"
    status: "True"
    type: InstanceExists
  - lastTransitionTime: "2026-04-18T04:05:38Z"
    status: "True"
    type: Terminable
  lastUpdated: "2026-04-18T04:09:20Z"
  nodeRef:
    kind: Node
    name: ip-10-0-63-189.us-west-2.compute.internal
    uid: f01fd1b0-aa11-4124-9f06-33e595eb9e39
  phase: Running
  providerStatus:
    conditions:
    - lastTransitionTime: "2026-04-18T04:05:40Z"
      message: Machine successfully created
      reason: MachineCreationSucceeded
      status: "True"
      type: MachineCreation
    instanceId: i-0434f6b18f1017460
    instanceState: running
