apiVersion: v1
kind: Node
metadata:
  annotations:
    cloud.network.openshift.io/egress-ipconfig: '[{"interface":"ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3-sfw9k-nic","ifaddr":{"ipv4":"10.0.128.0/17"},"capacity":{"ip":255}}]'
    csi.volume.kubernetes.io/nodeid: '{"disk.csi.azure.com":"ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3-sfw9k","file.csi.azure.com":"ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3-sfw9k"}'
    k8s.ovn.org/host-cidrs: '["10.0.128.7/17"]'
    k8s.ovn.org/l3-gateway-config: '{"default":{"mode":"shared","bridge-id":"br-ex","interface-id":"br-ex_ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3-sfw9k","mac-address":"00:22:48:06:fc:1c","ip-addresses":["10.0.128.7/17"],"ip-address":"10.0.128.7/17","next-hops":["10.0.128.1"],"next-hop":"10.0.128.1","node-port-enable":"true","vlan-id":"0"}}'
    k8s.ovn.org/node-chassis-id: 9ced0afb-c364-4967-8793-75a76d51318b
    k8s.ovn.org/node-encap-ips: '["10.0.128.7"]'
    k8s.ovn.org/node-id: "8"
    k8s.ovn.org/node-masquerade-subnet: '{"ipv4":"169.254.0.0/17","ipv6":"fd69::/112"}'
    k8s.ovn.org/node-primary-ifaddr: '{"ipv4":"10.0.128.7/17"}'
    k8s.ovn.org/node-subnets: '{"default":["10.130.2.0/23"]}'
    k8s.ovn.org/node-transit-switch-port-ifaddr: '{"ipv4":"100.88.0.8/16"}'
    k8s.ovn.org/zone-name: ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3-sfw9k
    machine.openshift.io/machine: openshift-machine-api/ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3-sfw9k
    machineconfiguration.openshift.io/controlPlaneTopology: HighlyAvailable
    machineconfiguration.openshift.io/currentConfig: rendered-worker-599001164df5ff735998ccc4024b117b
    machineconfiguration.openshift.io/desiredConfig: rendered-worker-599001164df5ff735998ccc4024b117b
    machineconfiguration.openshift.io/desiredDrain: uncordon-rendered-worker-599001164df5ff735998ccc4024b117b
    machineconfiguration.openshift.io/lastAppliedDrain: uncordon-rendered-worker-599001164df5ff735998ccc4024b117b
    machineconfiguration.openshift.io/lastObservedServerCAAnnotation: "false"
    machineconfiguration.openshift.io/lastSyncedControllerConfigResourceVersion: "49749"
    machineconfiguration.openshift.io/reason: ""
    machineconfiguration.openshift.io/state: Done
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2026-04-17T22:35:35Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: Standard_D4s_v3
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: westus
    failure-domain.beta.kubernetes.io/zone: "0"
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3-sfw9k
    kubernetes.io/os: linux
    node-role.kubernetes.io/worker: ""
    node.kubernetes.io/instance-type: Standard_D4s_v3
    node.openshift.io/os_id: rhcos
    topology.disk.csi.azure.com/zone: ""
    topology.kubernetes.io/region: westus
    topology.kubernetes.io/zone: "0"
  name: ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3-sfw9k
  resourceVersion: "50503"
  uid: 781a25f4-5641-4c1a-bac8-a2bdb19ff57b
spec:
  providerID: azure:///subscriptions/72e3a972-58b0-4afc-bd4f-da89b39ccebd/resourceGroups/ci-ln-wy83gzk-1d09d-m9g8v-rg/providers/Microsoft.Compute/virtualMachines/ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3-sfw9k
status:
  addresses:
  - address: 10.0.128.7
    type: InternalIP
  - address: ci-ln-wy83gzk-1d09d-m9g8v-worker-westus-v3-sfw9k
    type: Hostname
  allocatable:
    cpu: 3500m
    ephemeral-storage: "122076772149"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 15221088Ki
    pods: "250"
  capacity:
    cpu: "4"
    ephemeral-storage: 133626860Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 16372064Ki
    pods: "250"
  conditions:
  - lastHeartbeatTime: "2026-04-17T22:38:39Z"
    lastTransitionTime: "2026-04-17T22:35:35Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2026-04-17T22:38:39Z"
    lastTransitionTime: "2026-04-17T22:35:35Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2026-04-17T22:38:39Z"
    lastTransitionTime: "2026-04-17T22:35:35Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2026-04-17T22:38:39Z"
    lastTransitionTime: "2026-04-17T22:37:10Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b58f195d83635a36d05f1e187afa32e698ce14d509c03b47f984a01a87a5a681
    sizeBytes: 1637463217
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8484023cfbf54b5e883da4b193758e0e0b9d7417a83a4ec2e046e553917709a8
    sizeBytes: 1238203929
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:cbc38b69f3b3aadfc71efc9b42472b4cf70ba3429850cf865cfcf98cfaa22b5e
    sizeBytes: 991850082
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:0a09f5a3ba4f60cce0145769509bab92553c8075d210af4ac058965d2ae11efa
    sizeBytes: 876160834
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:f6de759ca6292a8862645c8ffe0cba0df532d164a0d89da44e9af9ca59c7b063
    sizeBytes: 870379576
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:5e12e4dc52214d3ada5ba5106caebe079eac1d9292c2571a5fe83411ce8e900d
    sizeBytes: 683195416
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9ffb7b6f7121b0735b4d34a53a4eac6d866b654d5eff8205ae1fce7b24d4be5c
    sizeBytes: 677942898
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ec8fd46dfb35ed10e8f98933166f69ce579c2f35b8db03d21e4c34fc544553e4
    sizeBytes: 621648710
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:08bd6463f232a07901d5291f750e58489438e593771d3de3f661a6b9639ec281
    sizeBytes: 593003784
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:c6a4383333a1fd6d05c3f60ec793913f7937ee3d77f002d85e6c61e20507bf55
    sizeBytes: 582154903
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:278800effa48796fe57c6d705d300c69483e81252e6a7fbfaa4959614be73d7c
    sizeBytes: 577622845
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:112a03f2411f871cdaca5f20daef71024dac710113d5f30897117a5a02f6b6f5
    sizeBytes: 557428271
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:21b4c9cf268bb7abef7af187cd775d3f74d0bd33626250095428d53b705ee946
    sizeBytes: 528956487
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:fc78ae6ff45a27c111fff14e9d15a2e9982f97577722fe519630a018ebd64a5e
    sizeBytes: 522865274
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:77fff570657d2fa0bfb709b2c8b6665bae0bf90a2be981d8dbca56c674715098
    sizeBytes: 511227324
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:00534ec2823bb58616c955b80cb8fed0fb9193cd2fa3b9b06089c9692c33175b
    sizeBytes: 505813735
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:2c4d5a681595e428ff4b5083648c13615eed80be9084a3d3fc68a0295079cb12
    sizeBytes: 484187929
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:0d56d92f7ce705f8e4d8034bc9a343422ba719dd870b0ac4f1e24a46fe6360e4
    sizeBytes: 481637508
  - names:
    - quay.io/openshift-logging/promtail@sha256:37c4c781fb99ad787118c4ebebc1d81ac6415ba62c4d5965e3852e5721509909
    - quay.io/openshift-logging/promtail@sha256:f0e53a97d686fdab3ae1a4b43176dd0105ce53887b0faba528f3497f7765d26f
    - quay.io/openshift-logging/promtail:v2.9.8
    sizeBytes: 478481622
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:d12d0dc7eb86bbedf6b2d7689a28fd51f0d928f720e4a6783744304297c661ed
    sizeBytes: 465090934
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:759fb1d5353dbbadd443f38631d977ca3aed9787b873be05cc9660532a252739
    sizeBytes: 448828620
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:78976f244a2a7101390df281688f339864f3e7eda6531df18225022c768ca0b3
    sizeBytes: 423750986
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:822c188c94c3c932f479e841d4ef3a55739f09d1670a47cee79ec5397591653c
    sizeBytes: 423367000
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:0bccc03fd9ffe278e15c8f4be1db030307e4cd5020b78d711fc62f104fd6a980
    sizeBytes: 417688124
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:0e66fd50be6f83ce321a566dfb76f3725b597374077d5af13813b928f6b1267e
    sizeBytes: 411587146
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:e3a494212f1ba17f0f0980eef583218330eccb56eadf6b8cb0548c76d99b5014
    sizeBytes: 407347125
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:53d66d524ca3e787d8dbe30dbc4d9b8612c9cebd505ccb4375a8441814e85422
    sizeBytes: 396521761
  nodeInfo:
    architecture: amd64
    bootID: b007ae37-1ebd-446e-a6b1-20bb04c78cb5
    containerRuntimeVersion: cri-o://1.31.13-8.rhaos4.18.gitd78977c.el9
    kernelVersion: 5.14.0-427.115.1.el9_4.x86_64
    kubeProxyVersion: v1.31.14
    kubeletVersion: v1.31.14
    machineID: 778069ab177b4155bfd31e5e22deb489
    operatingSystem: linux
    osImage: Red Hat Enterprise Linux CoreOS 418.94.202603181125-0
    systemUUID: 6fe8995c-6975-44df-85e2-573f4cf4e65a
  runtimeHandlers:
  - features:
      recursiveReadOnlyMounts: true
      userNamespaces: true
    name: crun
  - features:
      recursiveReadOnlyMounts: true
      userNamespaces: true
    name: ""
  - features:
      recursiveReadOnlyMounts: true
      userNamespaces: true
    name: runc
