apiVersion: v1
kind: Node
metadata:
  annotations:
    cloud.network.openshift.io/egress-ipconfig: '[{"interface":"ci-ln-rm0x8pk-1d09d-vkpbd-worker-eastus21-v5-75rk2-nic","ifaddr":{"ipv4":"10.0.128.0/17"},"capacity":{"ip":255}}]'
    csi.volume.kubernetes.io/nodeid: '{"disk.csi.azure.com":"ci-ln-rm0x8pk-1d09d-vkpbd-worker-eastus21-v5-75rk2","file.csi.azure.com":"ci-ln-rm0x8pk-1d09d-vkpbd-worker-eastus21-v5-75rk2"}'
    k8s.ovn.org/host-cidrs: '["10.0.128.8/17"]'
    k8s.ovn.org/l3-gateway-config: '{"default":{"mode":"shared","bridge-id":"br-ex","interface-id":"br-ex_ci-ln-rm0x8pk-1d09d-vkpbd-worker-eastus21-v5-75rk2","mac-address":"60:45:bd:af:63:8d","ip-addresses":["10.0.128.8/17"],"ip-address":"10.0.128.8/17","next-hops":["10.0.128.1"],"next-hop":"10.0.128.1","node-port-enable":"true","vlan-id":"0"}}'
    k8s.ovn.org/layer2-topology-version: "2.0"
    k8s.ovn.org/node-chassis-id: d2955303-1b5b-4835-b524-a0b326bd3c24
    k8s.ovn.org/node-encap-ips: '["10.0.128.8"]'
    k8s.ovn.org/node-id: "9"
    k8s.ovn.org/node-masquerade-subnet: '{"ipv4":"169.254.0.0/17","ipv6":"fd69::/112"}'
    k8s.ovn.org/node-primary-ifaddr: '{"ipv4":"10.0.128.8/17"}'
    k8s.ovn.org/node-subnets: '{"default":["10.131.2.0/23"]}'
    k8s.ovn.org/node-transit-switch-port-ifaddr: '{"ipv4":"100.88.0.9/16"}'
    k8s.ovn.org/zone-name: ci-ln-rm0x8pk-1d09d-vkpbd-worker-eastus21-v5-75rk2
    machine.openshift.io/machine: openshift-machine-api/ci-ln-rm0x8pk-1d09d-vkpbd-worker-eastus21-v5-75rk2
    machineconfiguration.openshift.io/controlPlaneTopology: HighlyAvailable
    machineconfiguration.openshift.io/currentConfig: rendered-worker-ecf54fcb3e0b95dc1fcac159491e0804
    machineconfiguration.openshift.io/desiredConfig: rendered-worker-ecf54fcb3e0b95dc1fcac159491e0804
    machineconfiguration.openshift.io/desiredDrain: uncordon-rendered-worker-ecf54fcb3e0b95dc1fcac159491e0804
    machineconfiguration.openshift.io/firstPivotConfig: rendered-worker-ecf54fcb3e0b95dc1fcac159491e0804
    machineconfiguration.openshift.io/lastAppliedDrain: uncordon-rendered-worker-ecf54fcb3e0b95dc1fcac159491e0804
    machineconfiguration.openshift.io/lastObservedServerCAAnnotation: "false"
    machineconfiguration.openshift.io/lastSyncedControllerConfigResourceVersion: "39867"
    machineconfiguration.openshift.io/reason: ""
    machineconfiguration.openshift.io/state: Done
    tuned.openshift.io/bootcmdline: ""
    tuned.openshift.io/bootcmdline-deps: 4.22.0-0.nightly-2026-04-16-185359,default:1
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2026-04-17T19:48:51Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: Standard_D4s_v5
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: eastus2
    failure-domain.beta.kubernetes.io/zone: eastus2-1
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: ci-ln-rm0x8pk-1d09d-vkpbd-worker-eastus21-v5-75rk2
    kubernetes.io/os: linux
    node-role.kubernetes.io/worker: ""
    node.kubernetes.io/instance-type: Standard_D4s_v5
    node.openshift.io/os_id: rhel
    topology.disk.csi.azure.com/zone: eastus2-1
    topology.kubernetes.io/region: eastus2
    topology.kubernetes.io/zone: eastus2-1
  name: ci-ln-rm0x8pk-1d09d-vkpbd-worker-eastus21-v5-75rk2
  resourceVersion: "44363"
  uid: bcbda23f-a26b-4b2f-9afd-a999d2e24eb4
spec:
  providerID: azure:///subscriptions/72e3a972-58b0-4afc-bd4f-da89b39ccebd/resourceGroups/ci-ln-rm0x8pk-1d09d-vkpbd-rg/providers/Microsoft.Compute/virtualMachines/ci-ln-rm0x8pk-1d09d-vkpbd-worker-eastus21-v5-75rk2
status:
  addresses:
  - address: 10.0.128.8
    type: InternalIP
  - address: ci-ln-rm0x8pk-1d09d-vkpbd-worker-eastus21-v5-75rk2
    type: Hostname
  allocatable:
    cpu: 3500m
    ephemeral-storage: "122076772149"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 15214832Ki
    pods: "250"
  capacity:
    cpu: "4"
    ephemeral-storage: 133626860Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 16365808Ki
    pods: "250"
  conditions:
  - lastHeartbeatTime: "2026-04-17T19:50:34Z"
    lastTransitionTime: "2026-04-17T19:48:51Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2026-04-17T19:50:34Z"
    lastTransitionTime: "2026-04-17T19:48:51Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2026-04-17T19:50:34Z"
    lastTransitionTime: "2026-04-17T19:48:51Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2026-04-17T19:50:34Z"
    lastTransitionTime: "2026-04-17T19:49:48Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  features:
    supplementalGroupsPolicy: true
  images:
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:047bc67c8325087d83a4cceac5a816d4cae0f451326d3d93f6ed95d5b4f1e66e
    sizeBytes: 1523459381
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:965564a81616e17978f03959111d1db499583e8e486125739ae9fc7989fce57c
    sizeBytes: 1493153797
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:abab92d447759cdedba8043d31da3496f795e4c910cc6e60914441221d639ffe
    sizeBytes: 1006758153
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:fd6fd308aa5eb6387e454359b7a132afc88c78439201206f00c9f3954b2fda9f
    sizeBytes: 1000977826
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4f6b346f8ca4fd184663e9e3a7e6df978daeb9f60a365d76c45bd37ccd526e8c
    sizeBytes: 772910453
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:808495766f26fc3f2c2b6b836c4139da7e9559f9ee01017d3de2a90ae4b97089
    sizeBytes: 667284413
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:99d587d8a6deac96214a3cd9be4100afdd209f5d7035c0754997e9bb228f6e14
    sizeBytes: 664124915
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3cc959735303e09911d931a8ffd4b475987cca954b882596c271699adc2ad6a6
    sizeBytes: 629447262
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:909303218d5b14674aabe2d894b084701bf98c4fddfc099447855a5090239bb8
    sizeBytes: 533936598
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:eb3908bbc1eaa4f598590b3ca29e5dcbd5f9797ab2c92bb54d001c30fc6daa7c
    sizeBytes: 517270911
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9d581acf8ff9415b78cb3a72342183ebd6404138484187723319253326615f05
    sizeBytes: 505940199
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:125b54865cdad5a1cf3ec05151515bd0124eba6ee50945c21d697b357b556695
    sizeBytes: 495910664
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:f2fecf85302d67cffd08fb328f2eeec381f4edeb6ff70dda9320e23180ada919
    sizeBytes: 494699429
  - names:
    - quay.io/openshift-logging/promtail@sha256:37c4c781fb99ad787118c4ebebc1d81ac6415ba62c4d5965e3852e5721509909
    - quay.io/openshift-logging/promtail@sha256:f0e53a97d686fdab3ae1a4b43176dd0105ce53887b0faba528f3497f7765d26f
    - quay.io/openshift-logging/promtail:v2.9.8
    sizeBytes: 478481622
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1fe26db4717d8e56f7a9b5c411af0fd4f47003cdf087113667612a94232d5788
    sizeBytes: 432382230
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:cb16569394fa384ed1e6b3b62d1f3f7908ca5a4b1f93deac575ff3c2bce200bf
    sizeBytes: 428546159
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3d4a4008021db07716a52b450080ab771ef8f333f091ce6cbf3bbe222a86b74f
    sizeBytes: 425120052
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3fb7c7319038c6d5e003d138270e78613223be4f4e252a6327d599e4182d01d3
    sizeBytes: 405825910
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ba63800d7599664c73936321042e2787aafecddbe607843ae8c91f7f5faf7497
    sizeBytes: 403429800
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:78863b6ff0d3f8e522075c80e7fba2df4a305eaaa3da8a3304d00bd4c35996a4
    sizeBytes: 367386385
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:dee202ae1d67cdcf9771d0dbdf552d2306d8964fca12316966966a5e3da5f76d
    sizeBytes: 365747209
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:c49102b83ab6e24123d2af4bb19a4fc2f573400a120cf382eee593860d0f8309
    sizeBytes: 334053226
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:cc84f1cd2c13ffb488ff8f8b7d00eaf846f9f69d0211119c9bca8765f94eb249
    sizeBytes: 333163719
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:69035a0d0e216794443170cdb7ec31f96d1aa5de9ea4533dff57c229ee5d5052
    sizeBytes: 319723988
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ffdb03f74c9d687fb793566a6b76b2dd8f39c547aeb807b88a5d1cba52f533ac
    sizeBytes: 319513063
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:fa12ccf2f6ca4022358f3ea68ae1ba47adfeea2b514f5c5c3a39f0cbb2264f5b
    sizeBytes: 308079829
  - names:
    - registry.redhat.io/openshift4/ose-oauth-proxy-rhel9@sha256:eb7244813fd299cb3b125799b5a03bf93e75110308331f8db1e3cbae3d739b0e
    - registry.redhat.io/openshift4/ose-oauth-proxy-rhel9@sha256:f85223c9693ecb0e69e156fe28c980d0d4edeaf823142327b0a4033e0fc89074
    - registry.redhat.io/openshift4/ose-oauth-proxy-rhel9:latest
    sizeBytes: 304600334
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ca1c538f9a91ceb512229fd6f3b292551046ec05910edee4fac8637ff4938b3c
    sizeBytes: 303752278
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:6592f41fdaa2b0ef2f3f10e23e4f2f41f029be31279ba63b749d956d68d023d2
    sizeBytes: 300687820
  - names:
    - quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:c244a9c834031b2eabb0986540fc97dc7ec5ec1a19d0e655b99c9cafca146ad8
    sizeBytes: 291433389
  - names:
    - quay.io/observatorium/token-refresher@sha256:1d99cf24a5a1d74daf73ac47b4e757f13ed5408e7441642bb7ad02bb71551841
    - quay.io/observatorium/token-refresher@sha256:721366017a72606d0022be291c40c300e7cdba2a45f79a485ce5790d865db47d
    - quay.io/observatorium/token-refresher:latest
    sizeBytes: 10461829
  nodeInfo:
    architecture: amd64
    bootID: b374b71b-10a2-4010-a4c4-d03113e996c0
    containerRuntimeVersion: cri-o://1.35.2-8.rhaos4.22.git5269e16.el9
    kernelVersion: 5.14.0-687.5.1.el9_8.x86_64
    kubeProxyVersion: ""
    kubeletVersion: v1.35.3
    machineID: 78800c3b03f24f728751f9994cb2c72a
    operatingSystem: linux
    osImage: Red Hat Enterprise Linux CoreOS 9.8.20260415-0 (Plow)
    systemUUID: 68218b62-5f2b-43d7-aea5-17d4f0a893f5
  runtimeHandlers:
  - features:
      recursiveReadOnlyMounts: true
      userNamespaces: true
    name: crun
  - features:
      recursiveReadOnlyMounts: true
      userNamespaces: true
    name: ""
  - features:
      recursiveReadOnlyMounts: true
      userNamespaces: true
    name: runc
