apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: "worker"
  name: 99-worker-osimageurl
spec:
  osImageURL: quay.io/sdodsonrht/4.21.11:zstd
